// <auto-generated />
namespace Lib;

// The designer half of a partial class. Its mere existence marks the whole
// type as generated, even though the members below live in a hand-written
// file.
public partial class Form
{
    private void InitializeComponent()
    {
    }
}
