use std::path::PathBuf;

use roe::commands::dead_code::analyze;
use roe::model::FindingKind;

fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name)
}

/// Sorted (kind, name) pairs for stable assertions.
fn findings(name: &str, aggressive: bool) -> Vec<(FindingKind, String)> {
    let analysis = analyze(&fixture(name), aggressive, &[]).expect("analysis should succeed");
    let mut pairs: Vec<(FindingKind, String)> = analysis
        .result
        .findings
        .iter()
        .map(|f| (f.kind, f.name.clone()))
        .collect();
    pairs.sort_by(|a, b| a.1.cmp(&b.1));
    pairs
}

fn file(kind_name: &str) -> (FindingKind, String) {
    (FindingKind::UnusedFile, kind_name.to_string())
}

fn ty(kind_name: &str) -> (FindingKind, String) {
    (FindingKind::UnusedType, kind_name.to_string())
}

fn member(kind_name: &str) -> (FindingKind, String) {
    (FindingKind::UnusedMember, kind_name.to_string())
}

fn assert_findings(actual: Vec<(FindingKind, String)>, mut expected: Vec<(FindingKind, String)>) {
    expected.sort_by(|a, b| a.1.cmp(&b.1));
    assert_eq!(actual, expected);
}

#[test]
fn console_app_finds_dead_class_and_member() {
    assert_findings(
        findings("console_app", false),
        vec![
            file("ConsoleApp/DeadClass.cs"),
            member("ConsoleApp.ConsoleGreeter.UnusedHelper"),
        ],
    );
}

#[test]
fn with_tests_test_usage_counts_and_library_mode_protects_public_api() {
    // No executable → library mode: public Calculator.Add stays (used by
    // tests anyway); only internal dead code is flagged.
    assert_findings(
        findings("with_tests", false),
        vec![
            file("Lib/UnusedInternal.cs"),
            member("Lib.Calculator.InternalUnused"),
        ],
    );
}

#[test]
fn webapi_controllers_and_di_registrations_are_roots() {
    // HealthController: alive via controller convention + [HttpGet].
    // SystemClock: alive only through AddScoped<IClock, SystemClock>().
    // IClock.Now/SystemClock.Now: interface dispatch.
    assert_findings(
        findings("webapi", false),
        vec![file("WebApi/DeadHelper.cs")],
    );
}

#[test]
fn library_only_flags_internal_and_private_only() {
    assert_findings(
        findings("library_only", false),
        vec![
            file("Lib2/InternalDead.cs"),
            member("Lib2.PublicApi.neverUsed"),
        ],
    );
}

#[test]
fn bare_directory_without_project_files() {
    assert_findings(findings("bare_dir", false), vec![file("Dead.cs")]);
}

#[test]
fn generated_files_are_reference_only_and_never_flagged() {
    // Kept/FromGenerated referenced only from Bindings.g.cs; designer and
    // <auto-generated>-header files declare unreferenced types.
    assert_findings(findings("generated", false), vec![]);
}

#[test]
fn nested_static_class_reached_via_qualified_member_access_is_not_dead() {
    // Tuning.Scores.Base: value-position access through a nested static
    // class. Scores must resolve like a qualified type path, not just the
    // leaf Base member, or it's reported as an unused type.
    assert_findings(findings("nested_static_class", false), vec![]);
}

#[test]
fn compiler_polyfills_are_never_flagged_dead() {
    // IsExternalInit is a hand-written polyfill needed for `init` accessors
    // on netstandard2.1 — only the compiler references it (emitted into IL),
    // so it must never be reported as an unused file/type.
    assert_findings(findings("compiler_polyfills", false), vec![]);
}

#[test]
fn partial_types_merge_across_files() {
    // Widget: one part referenced → nothing in either part flagged (Pong is
    // exempt: without obj/ the generated half of partials is invisible).
    // NeverUsed: merged type dead → both files are dead files, the type
    // finding is subsumed.
    assert_findings(
        findings("partial_types", false),
        vec![
            file("Part/NeverUsed.Part1.cs"),
            file("Part/NeverUsed.Part2.cs"),
        ],
    );
}

#[test]
fn kill_list_keeps_every_false_positive_candidate() {
    // The would-be false positives that must NOT appear:
    // - PoliteGreeter.Greet (interface-only dispatch)
    // - Circle.Render (override-only usage)
    // - SqlRepo/Worker (DI generic registration), Worker.StartAsync/StopAsync
    //   (external IHostedService heuristic)
    // - UserDto + auto-properties (serializer binding)
    // - StringExtensions.Shout (extension method, ungated)
    // - Order.Total (nameof), Migration001 (typeof)
    // - Program.OnClicked (event handler +=)
    // - MathHelper.Square (using static)
    // - SecuredThing ([Authorize] attribute-rooted), AuthorizeAttribute
    //   (attribute name shorthand)
    // - Status.Legacy (enum member, default mode)
    // - Pair.Deconstruct (invoked implicitly by `var (a, b) = ...`)
    //
    // True positives that MUST appear:
    // - DeadService (type gate: live.Process() elsewhere must not save it)
    // - ClusterHost.unusedField + DeadHelperMethod (dead cluster)
    assert_findings(
        findings("kill_list", false),
        vec![
            ty("Kill.DeadService"),
            member("Kill.ClusterHost.unusedField"),
            member("Kill.ClusterHost.DeadHelperMethod"),
        ],
    );
}

#[test]
fn kill_list_aggressive_flags_enum_members_and_auto_properties() {
    let actual = findings("kill_list", true);
    // Aggressive adds the serialization-prone members that default mode
    // exempts; Order.Total survives because nameof() references it and
    // Status.Active because it is named in Program.
    let must_appear = [
        member("Kill.Status.Legacy"),
        member("Kill.UserDto.Name"),
        member("Kill.UserDto.UnreadCount"),
    ];
    for expected in &must_appear {
        assert!(
            actual.contains(expected),
            "missing {expected:?} in {actual:?}"
        );
    }
    let must_not_appear = [member("Kill.Order.Total"), member("Kill.Status.Active")];
    for unexpected in &must_not_appear {
        assert!(!actual.contains(unexpected), "unexpected {unexpected:?}");
    }
}

#[test]
fn manual_roots_rescue_symbols() {
    let analysis = analyze(
        &fixture("console_app"),
        false,
        &["ConsoleApp.ConsoleGreeter.UnusedHelper".to_string()],
    )
    .expect("analysis should succeed");
    let names: Vec<&str> = analysis
        .result
        .findings
        .iter()
        .map(|f| f.name.as_str())
        .collect();
    assert!(!names.contains(&"ConsoleApp.ConsoleGreeter.UnusedHelper"));
}

#[test]
fn nonexistent_path_errors() {
    assert!(analyze(&fixture("does_not_exist"), false, &[]).is_err());
}

#[test]
fn inline_suppression_comments_filter_findings() {
    // SuppressedType, BareSuppressed, TrailingSuppressed, and the wholly-dead
    // WhollyDeadFile are all suppressed via inline comments. WrongRuleType is
    // annotated with a rule name that doesn't match its actual finding kind,
    // so it must still be reported (proves rule filtering isn't a no-op).
    // TrulyDeadType and UnannotatedDead carry no comment at all.
    assert_findings(
        findings("inline_suppress", false),
        vec![
            ty("InlineSuppress.TrulyDeadType"),
            ty("InlineSuppress.WrongRuleType"),
            member("InlineSuppress.HelperHost.UnannotatedDead"),
        ],
    );
}
