mod walk;

use lasso::{Spur, ThreadedRodeo};
use rayon::prelude::*;
use smallvec::SmallVec;

use crate::model::{FileId, Modifiers, SourceFile, SymbolKind};

/// Origin sentinel for references that don't sit inside any declaration
/// (top-level statements, assembly attributes).
pub const FILE_ROOT: u32 = u32::MAX;

pub type NamePath = SmallVec<[Spur; 2]>;

#[derive(Debug)]
pub struct RawDecl {
    pub name: Spur,
    pub kind: SymbolKind,
    /// Enclosing namespace segments (types only; empty for members).
    pub namespace: NamePath,
    /// Local index of the containing type declaration.
    pub parent: Option<u32>,
    pub modifiers: Modifiers,
    /// Last segment of each attribute on this declaration.
    pub attributes: SmallVec<[Spur; 2]>,
    /// base_list entries (types only), as raw name paths.
    pub base_names: SmallVec<[NamePath; 2]>,
    pub is_explicit_interface_impl: bool,
    /// Method whose first parameter has a `this` modifier — call sites never
    /// name the containing static class, so the BFS must not type-gate it.
    pub is_extension_method: bool,
    /// Auto-property: every accessor is bodyless (`{ get; set; }`).
    pub is_auto_property: bool,
    /// Method has a block/arrow body (partial-method implementation half).
    pub has_body: bool,
    /// Generic arity (types only), part of the partial-merge key.
    pub arity: u8,
    pub line: u32,
    pub column: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RawRefKind {
    /// Definite type position — resolved with namespace scoping.
    Type,
    /// Definite member position (`x.Name`) — resolved by name-set matching.
    Member,
    /// Bare identifier in expression position — could be either; matched as
    /// both (over-marking is the safe direction).
    Ambient,
    /// Attribute name — matched as a type, probing both `N` and `NAttribute`.
    Attribute,
    /// Sole generic argument of an invocation (`GetExports<I>()`,
    /// `AddHostedService<W>()`) — assembly-scan/DI registration pattern, so
    /// implementations of the named type must be treated as live.
    ScanTarget,
}

#[derive(Debug)]
pub struct RawRef {
    pub kind: RawRefKind,
    pub path: NamePath,
    /// Index into `FileFacts::decls`, or FILE_ROOT.
    pub origin: u32,
}

#[derive(Debug)]
pub struct UsingEntry {
    pub path: Vec<Spur>,
    pub alias: Option<Spur>,
    pub is_global: bool,
    pub is_static: bool,
}

#[derive(Debug)]
pub struct FileFacts {
    pub file: FileId,
    pub decls: Vec<RawDecl>,
    pub refs: Vec<RawRef>,
    pub usings: Vec<UsingEntry>,
    pub has_top_level_statements: bool,
    /// Tree contained ERROR nodes — resolution degrades to name matching.
    pub has_errors: bool,
    /// Generated by path pattern or <auto-generated> header.
    pub is_generated: bool,
}

impl FileFacts {
    fn empty(file: FileId, is_generated: bool) -> Self {
        Self {
            file,
            decls: Vec::new(),
            refs: Vec::new(),
            usings: Vec::new(),
            has_top_level_statements: false,
            has_errors: false,
            is_generated,
        }
    }
}

pub(crate) fn make_parser() -> tree_sitter::Parser {
    let mut parser = tree_sitter::Parser::new();
    parser
        .set_language(&tree_sitter_c_sharp::LANGUAGE.into())
        .expect("C# grammar is ABI-compatible with the linked tree-sitter runtime");
    parser
}

/// Parse and extract every file in parallel. One parser per rayon worker
/// (tree-sitter parsers are Send but not Sync).
pub fn extract_all(files: &[SourceFile], rodeo: &ThreadedRodeo) -> Vec<FileFacts> {
    files
        .par_iter()
        .map_init(make_parser, |parser, file| {
            extract_file(parser, file, rodeo)
        })
        .collect()
}

fn extract_file(
    parser: &mut tree_sitter::Parser,
    file: &SourceFile,
    rodeo: &ThreadedRodeo,
) -> FileFacts {
    let Ok(source) = std::fs::read(&file.path) else {
        let mut facts = FileFacts::empty(file.id, file.is_generated);
        facts.has_errors = true;
        return facts;
    };

    let is_generated = file.is_generated || sniff_auto_generated(&source);

    let Some(tree) = parser.parse(&source, None) else {
        let mut facts = FileFacts::empty(file.id, is_generated);
        facts.has_errors = true;
        return facts;
    };

    let mut facts = walk::extract(file.id, &source, tree.root_node(), rodeo);
    facts.is_generated = is_generated;
    facts
}

/// Look for the conventional `<auto-generated` marker near the top of the
/// file (tools place it in a header comment).
fn sniff_auto_generated(source: &[u8]) -> bool {
    let head = &source[..source.len().min(1024)];
    let head = String::from_utf8_lossy(head);
    head.contains("<auto-generated")
}

#[cfg(test)]
pub(crate) fn extract_source(source: &str, rodeo: &ThreadedRodeo) -> FileFacts {
    let mut parser = make_parser();
    let tree = parser.parse(source.as_bytes(), None).expect("parse");
    walk::extract(FileId(0), source.as_bytes(), tree.root_node(), rodeo)
}
