use std::path::PathBuf;

use crate::model::{FileId, ProjectId};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectKind {
    /// OutputType Exe/WinExe.
    Exe,
    /// Default for SDK-style projects without an OutputType.
    Library,
    /// Sdk="Microsoft.NET.Sdk.Web" (implies Exe semantics).
    Web,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TestFramework {
    Xunit,
    Nunit,
    Mstest,
}

#[derive(Debug)]
pub struct DiscoveredProject {
    pub id: ProjectId,
    pub name: String,
    /// None for the bare-directory fallback project.
    pub csproj_path: Option<PathBuf>,
    pub root_dir: PathBuf,
    pub kind: ProjectKind,
    pub project_refs: Vec<ProjectId>,
    pub package_refs: Vec<String>,
    pub test_framework: Option<TestFramework>,
    /// ImplicitUsings enabled (SDK default namespace set).
    pub implicit_usings: bool,
    /// Extra global usings from <Using Include="..."/> items.
    pub extra_usings: Vec<String>,
    /// Ships as a NuGet package — public API is an external contract and is
    /// always treated as used.
    pub is_packable: bool,
}

impl DiscoveredProject {
    pub fn is_executable(&self) -> bool {
        matches!(self.kind, ProjectKind::Exe | ProjectKind::Web)
    }

    pub fn is_test(&self) -> bool {
        self.test_framework.is_some()
    }

    /// Benchmark/sample/demo executables are auxiliary consumers — their
    /// presence must not expose a library workspace's public API to analysis.
    pub fn is_auxiliary(&self) -> bool {
        let name = self.name.to_ascii_lowercase();
        ["benchmark", "sample", "example", "demo", "playground"]
            .iter()
            .any(|marker| name.contains(marker))
    }
}

#[derive(Debug)]
pub struct SourceFile {
    pub id: FileId,
    pub path: PathBuf,
    pub project: Option<ProjectId>,
    /// Generated by name pattern or location (obj/); declarations in generated
    /// files are reference-only roots and never flagged.
    pub is_generated: bool,
}

/// Everything the discovery stage produces.
#[derive(Debug)]
pub struct Workspace {
    pub root: PathBuf,
    pub projects: Vec<DiscoveredProject>,
    pub files: Vec<SourceFile>,
    /// Non-fatal problems encountered during discovery, reported to stderr.
    pub warnings: Vec<String>,
    /// True when no project has an obj/ directory (build outputs missing), in
    /// which case partial-type members get extra exemptions.
    pub missing_obj: bool,
}
