use std::path::{Path, PathBuf};

use globset::{Glob, GlobSet, GlobSetBuilder};

use crate::model::ProjectId;

/// A project's source-selection rules, derived from its csproj (or defaults
/// for the bare-directory fallback).
pub struct SourceRules {
    pub project: ProjectId,
    pub root_dir: PathBuf,
    pub default_compile_items: bool,
    pub include_set: Option<GlobSet>,
    pub literal_includes: Vec<PathBuf>,
    pub remove_set: Option<GlobSet>,
}

impl SourceRules {
    pub fn new(
        project: ProjectId,
        root_dir: PathBuf,
        default_compile_items: bool,
        compile_includes: &[String],
        compile_removes: &[String],
        warnings: &mut Vec<String>,
    ) -> Self {
        let mut literal_includes = Vec::new();
        let mut include_globs = Vec::new();
        for include in compile_includes {
            if include.contains('*') {
                include_globs.push(include.clone());
            } else {
                // Literal paths may point outside the project dir (../Shared).
                let path = root_dir.join(include);
                match crate::paths::canonicalize(&path).ok() {
                    Some(path) => literal_includes.push(path),
                    None => warnings.push(format!(
                        "Compile Include not found: {} (project {})",
                        path.display(),
                        root_dir.display()
                    )),
                }
            }
        }

        Self {
            project,
            root_dir: root_dir.clone(),
            default_compile_items,
            include_set: build_globset(&root_dir, &include_globs, warnings),
            literal_includes,
            remove_set: build_globset(&root_dir, compile_removes, warnings),
        }
    }

    /// Whether this project claims `path` (which must already be known to lie
    /// under the project's root_dir), honoring Compile Remove and, for
    /// old-style projects, explicit Compile Include lists.
    pub fn claims(&self, path: &Path) -> Claim {
        if self
            .remove_set
            .as_ref()
            .is_some_and(|set| set.is_match(path))
        {
            return Claim::Removed;
        }
        if self.default_compile_items {
            return Claim::Included;
        }
        if self
            .include_set
            .as_ref()
            .is_some_and(|set| set.is_match(path))
            || self.literal_includes.iter().any(|p| p == path)
        {
            return Claim::Included;
        }
        Claim::NotListed
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Claim {
    Included,
    /// Matched a Compile Remove pattern — intentionally excluded from the
    /// build, so we skip it entirely (flagging it would be noise).
    Removed,
    /// Old-style project without this file in its Compile list.
    NotListed,
}

fn build_globset(
    root_dir: &Path,
    patterns: &[String],
    warnings: &mut Vec<String>,
) -> Option<GlobSet> {
    if patterns.is_empty() {
        return None;
    }
    let mut builder = GlobSetBuilder::new();
    let mut any = false;
    for pattern in patterns {
        if pattern.contains("..") {
            warnings.push(format!("unsupported glob with '..': {pattern}"));
            continue;
        }
        let absolute = format!("{}/{}", root_dir.display(), pattern);
        match Glob::new(&absolute) {
            Ok(glob) => {
                builder.add(glob);
                any = true;
            }
            Err(error) => warnings.push(format!("invalid glob {pattern}: {error}")),
        }
    }
    if !any {
        return None;
    }
    builder.build().ok()
}

/// Generated-file detection by name/location. Content sniffing for
/// <auto-generated> headers happens at extraction time when the file is read.
pub fn is_generated_path(path: &Path) -> bool {
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_ascii_lowercase())
        .unwrap_or_default();
    name.ends_with(".g.cs")
        || name.ends_with(".g.i.cs")
        || name.ends_with(".generated.cs")
        || name.ends_with(".designer.cs")
        || name.ends_with(".assemblyinfo.cs")
        || name.ends_with(".assemblyattributes.cs")
        || path
            .components()
            .any(|c| c.as_os_str().eq_ignore_ascii_case("obj"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_path_patterns() {
        assert!(is_generated_path(Path::new("/x/Routes.g.cs")));
        assert!(is_generated_path(Path::new("/x/Form1.Designer.cs")));
        assert!(is_generated_path(Path::new("/x/Models.generated.cs")));
        assert!(is_generated_path(Path::new(
            "/x/obj/Debug/net8.0/App.GlobalUsings.g.cs"
        )));
        assert!(is_generated_path(Path::new("/x/MyApp.AssemblyInfo.cs")));
        assert!(!is_generated_path(Path::new("/x/Program.cs")));
        assert!(!is_generated_path(Path::new("/x/objects/Thing.cs")));
    }

    #[test]
    fn remove_globs_exclude_files() {
        let mut warnings = Vec::new();
        let rules = SourceRules::new(
            ProjectId(0),
            PathBuf::from("/proj"),
            true,
            &[],
            &["Legacy/**/*.cs".to_string()],
            &mut warnings,
        );
        assert_eq!(
            rules.claims(Path::new("/proj/Legacy/Old.cs")),
            Claim::Removed
        );
        assert_eq!(
            rules.claims(Path::new("/proj/Legacy/Sub/Old.cs")),
            Claim::Removed
        );
        assert_eq!(rules.claims(Path::new("/proj/New.cs")), Claim::Included);
        assert!(warnings.is_empty());
    }

    #[test]
    fn old_style_only_takes_listed_files() {
        let mut warnings = Vec::new();
        let rules = SourceRules::new(
            ProjectId(0),
            PathBuf::from("/proj"),
            false,
            &["Sub/*.cs".to_string()],
            &[],
            &mut warnings,
        );
        assert_eq!(rules.claims(Path::new("/proj/Sub/A.cs")), Claim::Included);
        assert_eq!(rules.claims(Path::new("/proj/Other.cs")), Claim::NotListed);
    }
}
