// <auto-generated />
namespace HealthMetrics;

internal class GeneratedThing
{
    public void Complex(int a, int b, int c, int d, int e, int f, int g)
    {
        if (a > 0 && b > 0 && c > 0 && d > 0 && e > 0 && f > 0 && g > 0)
        {
            DoSomething();
        }
    }

    private void DoSomething() { }
}
